management:
  endpoints:
    web:
      exposure:
        include: metrics,health,env
  endpoint:
    env:
      show-values: ALWAYS

spring:
  ai:
    ollama:
      base-url: http://myserver:11434
      chat:
        model: llama3.2
